[package]
name = "neunode-engine-api-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time", "sync", "fs"] }
jsonwebtoken = "9"
alloy = { workspace = true, features = ["rpc-types-engine", "rpc-types"] }
tracing = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
futures = "0.3"
