[package]
name = "neunode-verification"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["gauntlet", "spot-check", "repops"]
gauntlet = []
spot-check = []
repops = []
tee = []
tee-sim = []
tee-intel = ["tee", "dep:dcap-qvl"]
zk = []

[dependencies]
neunode-core = { path = "../neunode-core" }
neunode-crypto = { path = "../neunode-crypto" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
ts-rs = { workspace = true }
rand = { version = "0.8" }
dcap-qvl = { version = "=0.5.2", optional = true, default-features = false, features = ["std", "ring", "default-x509"] }
