[package]
name = "neunode-reputation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ts-rs = { workspace = true }
neunode-core = { path = "../neunode-core" }
neunode-crypto = { path = "../neunode-crypto" }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
neunode-identity = { path = "../neunode-identity" }
