[package]
name = "neunode-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
neunode-core = { path = "../neunode-core" }
neunode-crypto = { path = "../neunode-crypto" }
rocksdb = { workspace = true }
moka = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
