//! Predeployed contract addresses and bytecode for the Neunode genesis block.
//!
//! Contracts are deployed at deterministic addresses in the `0x0000...00XX` range.
//! Bytecode and storage are generated by `scripts/genesis_codegen.py` which deploys
//! all contracts on Anvil, extracts the deployed state, and remaps addresses to
//! the deterministic predeploy addresses.
//!
//! To regenerate: `python3 scripts/genesis_codegen.py`

use alloy::primitives::{address, Address, Bytes, B256};
use std::collections::BTreeMap;

/// JSON file generated by the codegen script, embedded at compile time.
const GENESIS_PREDEPLOYS_JSON: &str = include_str!("genesis_predeploys.json");

/// Descriptor for a contract predeployed at genesis.
#[derive(Debug, Clone)]
pub struct PredeployedContract {
    /// Human-readable name for logging and tooling.
    pub name: String,
    /// Deterministic address where the contract is deployed.
    pub address: Address,
    /// Deployed bytecode (runtime code, not init code).
    pub bytecode: Bytes,
    /// Pre-initialized storage slots (slot -> value).
    pub storage: BTreeMap<B256, B256>,
}

// Deterministic predeploy addresses.

/// Diamond proxy (EIP-2535) - entry point for all facets.
pub const DIAMOND_PROXY: Address = address!("0000000000000000000000000000000000001001");

/// NeunodeIdentity - DID registry for AI agents.
pub const NEUNODE_IDENTITY: Address = address!("0000000000000000000000000000000000001002");

/// NeunodeBounty - bounty state machine.
pub const NEUNODE_BOUNTY: Address = address!("0000000000000000000000000000000000001003");

/// NeunodeEscrow - bilateral escrow for bounty payments.
pub const NEUNODE_ESCROW: Address = address!("0000000000000000000000000000000000001004");

/// NeunodeRegistry - agent capability and endpoint registry.
pub const NEUNODE_REGISTRY: Address = address!("0000000000000000000000000000000000001005");

/// nCompute token - GPU/CPU hours resource token.
pub const COMPUTE_TOKEN: Address = address!("0000000000000000000000000000000000001006");

/// nTrain token - training compute resource token.
pub const TRAIN_TOKEN: Address = address!("0000000000000000000000000000000000001007");

/// nBandwidth token - bandwidth resource token.
pub const BANDWIDTH_TOKEN: Address = address!("0000000000000000000000000000000000001008");

/// nStorage token - storage resource token.
pub const STORAGE_TOKEN: Address = address!("0000000000000000000000000000000000001009");

/// ModelRegistry - model lineage DAG with content-addressed models.
pub const MODEL_REGISTRY: Address = address!("000000000000000000000000000000000000100a");

/// RoyaltySplitter - ERC-2981 royalty distribution with BFS lineage traversal.
pub const ROYALTY_SPLITTER: Address = address!("000000000000000000000000000000000000100b");

/// NeunodeGovernance - on-chain governance with staked token voting.
pub const NEUNODE_GOVERNANCE: Address = address!("000000000000000000000000000000000000100c");

/// StakingEscrow - inactivity decay manager.
pub const STAKING_ESCROW: Address = address!("000000000000000000000000000000000000100d");

/// BountyReview - 2-of-3 review committee for bounty submissions.
pub const BOUNTY_REVIEW: Address = address!("000000000000000000000000000000000000100e");

/// DiamondCutFacet - facet for adding/replacing/removing facets (EIP-2535).
pub const DIAMOND_CUT_FACET: Address = address!("0000000000000000000000000000000000001010");

/// DiamondLoupeFacet - facet for inspecting facets and selectors (EIP-2535).
pub const DIAMOND_LOUPE_FACET: Address = address!("0000000000000000000000000000000000001011");

/// EIP-4788 beacon roots contract (system predeploy for Cancun).
pub const BEACON_ROOTS: Address = address!("000F3df6D732807Ef1319fB7B8bB8522d0Beac02");

/// Returns all Neunode-specific predeployed contracts with real bytecode and storage.
///
/// Bytecode and storage are loaded from `genesis_predeploys.json`, which is generated
/// by deploying contracts on Anvil and extracting the resulting state. The state is
/// remapped so cross-contract references point to the deterministic predeploy addresses.
pub fn neunode_predeploys() -> Vec<PredeployedContract> {
    let json: serde_json::Value = serde_json::from_str(GENESIS_PREDEPLOYS_JSON)
        .expect("genesis_predeploys.json must be valid JSON");

    let predeploys = json
        .get("predeploys")
        .and_then(|v| v.as_array())
        .expect("genesis_predeploys.json must have a 'predeploys' array");

    predeploys
        .iter()
        .map(|entry| {
            let name = entry["name"].as_str().unwrap_or("unknown").to_string();
            let address: Address =
                entry["address"].as_str().and_then(|s| s.parse().ok()).unwrap_or(Address::ZERO);
            let bytecode: Bytes = entry["bytecode"]
                .as_str()
                .and_then(|s| if s == "0x" || s.is_empty() { None } else { s.parse().ok() })
                .unwrap_or_default();

            let storage = entry["storage"]
                .as_object()
                .map(|obj| {
                    obj.iter()
                        .filter_map(|(slot, value)| {
                            let slot: B256 = slot.parse().ok()?;
                            let val: B256 = value.as_str()?.parse().ok()?;
                            Some((slot, val))
                        })
                        .collect()
                })
                .unwrap_or_default();

            PredeployedContract { name, address, bytecode, storage }
        })
        .collect()
}

/// Returns all predeploy addresses as a vector, useful for quick lookups.
pub fn predeploy_addresses() -> Vec<Address> {
    neunode_predeploys().iter().map(|c| c.address).collect()
}
